---
apiVersion: v1
kind: Service
metadata:
  name: external-flask-demo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: flask-demo-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo-app
  template:
    metadata:
      labels:
        app: flask-demo-app
    spec:
      containers:
      - name: eks-demo-flask-app
        # image: <>.dkr.ecr.eu-central-1.amazonaws.com/eks_demo:0.1.0 # terraform output eks_demo_ecr_iamge_name
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 5000
        resources:
          requests:
            memory: 256Mi
            cpu: 350m
          limits:
            memory: 256Mi
            cpu: 350m
